import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';

// Importa la fuente de Google correctamente
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        {/* Aquí puedes incluir tus metadatos */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        {/* Aquí puedes incluir el contenido de tu aplicación */}
        {children}
      </body>
    </html>
  );
}
